export const ALL_PERMISSIONS = [
  "ACCESS_ADDRESS",
  "ACCESS_PUBLIC_KEY",
  "ACCESS_ALL_ADDRESSES",
  "SIGN_TRANSACTION",
  "ENCRYPT",
  "DECRYPT",
  "SIGNATURE",
  "ACCESS_ARWEAVE_CONFIG",
  "DISPATCH",
  "ACCESS_TOKENS",
];

export const REQUIRED_PERMISSIONS = [
  "ACCESS_ADDRESS",
  "ACCESS_PUBLIC_KEY",
  "SIGN_TRANSACTION",
  "ACCESS_ARWEAVE_CONFIG",
  "DISPATCH",
  "ACCESS_TOKENS",
];
